// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://jira.dev.apwide.com/rest/apwide/tem/1.1' | (string & {});
};

export type ErrorCollection = {
    errorMessages?: Array<string>;
    errors?: {
        [key: string]: string;
    };
    status?: number;
};

export type ApplicationRequest = {
    name: string;
    versionPrefix?: string;
    mappedProjectId?: number;
    createNewVersion?: boolean;
    deploymentConfiguration?: DeploymentConfiguration;
    deploymentAttributes?: Array<Attribute>;
    tierType?: TierType;
    parents?: Array<NamedReference>;
    tiers?: Array<NamedReference>;
    incomingDependencies?: Array<NamedReference>;
    outgoingDependencies?: Array<NamedReference>;
};

export type ApplicationResponse = {
    id: number;
    name: string;
    versionPrefix?: string;
    mappedProjectId?: number;
    createNewVersion?: boolean;
    deploymentConfiguration?: DeploymentConfiguration;
    deploymentAttributes?: Array<Attribute>;
    tierType?: TierType;
    parents?: Array<NamedReference>;
    tiers?: Array<NamedReference>;
    incomingDependencies?: Array<NamedReference>;
    outgoingDependencies?: Array<NamedReference>;
};

export const TierType = {
    STANDALONE: 'STANDALONE',
    TIER: 'TIER'
} as const;

export type TierType = typeof TierType[keyof typeof TierType];

export type Attribute = {
    id?: number;
    key?: string;
    type?: string;
    secured?: boolean;
    createdBy?: string;
    createdOn?: number;
    modifiedBy?: string;
    modifiedOn?: number;
};

export type AttributeValue = {
    name?: string;
    value?: string;
};

export type DeploymentResponse = {
    readonly deploymentId: number;
    readonly id: number;
    readonly environmentId: number;
    versionName?: string;
    versionId?: string;
    readonly deployer: string;
    readonly deployedTime: number;
    readonly categoryId: number;
    readonly categoryName: string;
    readonly applicationId: number;
    readonly applicationName: string;
    readonly endTime?: number;
    readonly duration?: number;
    buildNumber?: string;
    description?: string;
    orderedAttributes?: Array<AttributeValue>;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export type DeploymentRequest = {
    readonly deploymentId: number;
    readonly id: number;
    versionName?: string;
    versionId?: string;
    buildNumber?: string;
    description?: string;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export type DeploymentConfiguration = {
    showBuildNumber?: boolean;
    showDescription?: boolean;
    preventDeploymentMerge?: boolean;
    readonlyDeployedIssues?: boolean;
};

export type NamedReference = {
    id?: number;
    name?: string;
};

export type CreatableNamedReference = {
    id?: number;
    name?: string;
    /**
     * should we create reference if not existing
     */
    autoCreate?: boolean;
};

export type EnvironmentCategory = {
    id: number;
    name: string;
    order?: number;
    type?: EnvironmentCategoryType;
};

export const EnvironmentCategoryType = {
    DEVELOPMENT: 'DEVELOPMENT',
    TESTING: 'TESTING',
    STAGING: 'STAGING',
    PRODUCTION: 'PRODUCTION'
} as const;

export type EnvironmentCategoryType = typeof EnvironmentCategoryType[keyof typeof EnvironmentCategoryType];

export type EnvironmentStatus = {
    id: number;
    name: string;
    description?: string;
    color?: string;
    order?: number;
};

export type ScopedStatusChangeRequest = {
    scope?: EnvironmentsScope;
    status?: NamedReference;
    ignoredStatuses?: Array<NamedReference>;
    statusMapping?: {
        [key: string]: NamedReference;
    };
};

export type EnvironmentStatusChangeRequest = {
    id?: number;
    name?: string;
};

export type StatusChange = {
    readonly id: number;
    readonly categoryId: number;
    readonly categoryName: string;
    readonly applicationId: number;
    readonly applicationName: string;
    readonly statusName: string;
    status?: EnvironmentStatus;
    readonly changedBy: string;
    readonly changedOn: number;
    /**
     * endTime is not defined if status is the current one
     */
    readonly endTime?: number;
    /**
     * duration in ms. Only present if endTime is set
     */
    readonly duration?: number;
};

export type StatusChangeResult = {
    errors?: ErrorCollection;
    type?: StatusChangeResultType;
    previousStatus?: NamedReference;
    currentStatus?: NamedReference;
};

export const StatusChangeResultType = {
    IGNORED: 'IGNORED',
    CHANGED: 'CHANGED',
    FAILED: 'FAILED',
    NOT_MODIFIED: 'NOT_MODIFIED'
} as const;

export type StatusChangeResultType = typeof StatusChangeResultType[keyof typeof StatusChangeResultType];

export type StatusChangesResponse = {
    requestedStatus?: NamedReference;
    environments?: Array<EnvironmentStatusChange>;
};

export type EnvironmentStatusChange = {
    environment?: NamedReference;
    result?: StatusChangeResult;
};

export type EnvironmentsScope = {
    criteria?: Array<EnvironmentSearchCriterion>;
};

export type IssueDeployedRequest = {
    issueKey?: string;
    scope?: EnvironmentsScope;
    buildNumber?: string;
    versionName?: string;
    noEmailNotification?: boolean;
};

export type EnvironmentSearchCriterion = {
    name?: string;
    values?: Array<string>;
};

export type EnvironmentPermissionScheme = {
    id: number;
    name: string;
    description: string;
    roles: Array<string>;
    readonly global: boolean;
};

export type EnvironmentRequest = {
    application: NamedReference;
    category: NamedReference;
    name: string;
    description?: string;
    environmentPermissionScheme?: NamedReference;
    url?: string;
    parent?: NamedReference;
    tiers?: Array<NamedReference>;
    incomingDependencies?: Array<NamedReference>;
    outgoingDependencies?: Array<NamedReference>;
    attributes?: {
        [key: string]: string;
    };
    attributesToDelete?: Array<string>;
};

export type EnvironmentResponse = {
    readonly id?: number;
    application: ApplicationResponse;
    category: EnvironmentCategory;
    name: string;
    description?: string;
    environmentPermissionScheme?: EnvironmentPermissionScheme;
    status?: EnvironmentStatus;
    url?: string;
    deployment?: DeploymentResponse;
    readonly watched?: boolean;
    parent?: NamedReference;
    tiers?: Array<NamedReference>;
    incomingDependencies?: Array<NamedReference>;
    outgoingDependencies?: Array<NamedReference>;
    attributes?: {
        [key: string]: string;
    };
};

export type EnvironmentFilter = {
    criteria?: Array<EnvironmentSearchCriterion>;
    sortOrder?: string;
    sortBy?: string;
    limit?: number;
    offset?: number;
    expand?: boolean;
};

export type PaginatedEnvironmentResponse = {
    count: number;
    limit?: number;
    offset: number;
    environments?: Array<EnvironmentResponse>;
};

export type EnvironmentReference = {
    id?: number;
    name?: string;
    application?: NamedReference;
    category?: NamedReference;
};

export type EnvironmentReferenceResponse = {
    items?: Array<EnvironmentReference>;
};

export type CloneEnvironmentOverride = {
    name?: string;
};

export type CloneEnvironmentRequest = {
    from?: NamedReference;
    failIfNameExists?: boolean;
    includeTiers?: boolean;
    override?: CloneEnvironmentOverride;
};

export type OptionReferenceResource = {
    id?: number;
    name?: string;
};

export type OptionReferenceResourceResponse = {
    items?: Array<OptionReferenceResource>;
};

export type WatcherStatistics = {
    dumb?: string;
};

export type EnvironmentWatcher = {
    readonly id?: number;
    userKey?: string;
    userName?: string;
    environmentId: number;
    watchEnvironmentChanged: boolean;
    watchDeployedVersion: boolean;
    watchStatus: boolean;
    watchIssueAdded: boolean;
    watchIssueRemoved: boolean;
};

export type VersionInfoRequest = {
    application?: NamedReference;
    versionName: string;
    versionDescription?: string;
    /**
     * ISO-8601 date time format
     */
    startDate?: string;
    /**
     * ISO-8601 date time format
     */
    releaseDate?: string;
    released?: boolean;
    issues?: VersionIssues;
};

export type EnvironmentInfoRequest = {
    environmentSelector?: EnvironmentInfoSelector;
    deployment?: DeploymentInfo;
    environment: EnvironmentInfo;
    status?: NamedReference;
};

export type DeploymentInfo = {
    versionName?: string;
    /**
     * ISO-8601 date time format
     */
    deployedDate?: string;
    versionId?: string;
    buildNumber?: string;
    description?: string;
    attributes?: unknown;
    issues?: DeployedIssues;
};

export type EnvironmentInfoSelector = {
    environment?: CreatableNamedReference;
    application?: CreatableNamedReference;
    category?: CreatableNamedReference;
};

export type EnvironmentInfo = {
    name?: string;
    url?: string;
    attributes?: unknown;
};

export type EnvironmentInfoResponse = {
    environment: NamedReference;
    deployment?: DeploymentDetail;
    status?: NamedReference;
};

export type DeploymentDetail = {
    readonly id?: number;
    readonly environmentId?: number;
    versionName?: string;
    versionId?: string;
    readonly deployer?: string;
    /**
     * ISO-8601 date time format
     */
    deployedOn?: string;
    buildNumber?: string;
    description?: string;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export const DefaultBoolean = {
    YES: 'yes',
    NO: 'no',
    DEFAULT: 'default'
} as const;

export type DefaultBoolean = typeof DefaultBoolean[keyof typeof DefaultBoolean];

export type DeployedIssues = {
    addDoneIssuesFixedInVersion?: boolean;
    issueKeys?: Array<string>;
    jql?: string;
    noFixVersionUpdate?: boolean;
    sendJiraNotification?: boolean;
};

export type VersionIssues = {
    issueKeys?: Array<string>;
    jql?: string;
    sendJiraNotification?: boolean;
};

export type VersionInfo = {
    versionId: number;
    versionName: string;
    versionDescription?: string;
    startDate?: string;
    releaseDate?: string;
    released?: boolean;
    fixedIssues?: Array<string>;
};

export type VersionInfoResponse = {
    versions?: Array<VersionInfo>;
};

export type DeploymentResponseWritable = {
    versionName?: string;
    versionId?: string;
    buildNumber?: string;
    description?: string;
    orderedAttributes?: Array<AttributeValue>;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export type DeploymentRequestWritable = {
    versionName?: string;
    versionId?: string;
    buildNumber?: string;
    description?: string;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export type StatusChangeWritable = {
    status?: EnvironmentStatus;
};

export type EnvironmentPermissionSchemeWritable = {
    id: number;
    name: string;
    description: string;
    roles: Array<string>;
};

export type EnvironmentResponseWritable = {
    application: ApplicationResponse;
    category: EnvironmentCategory;
    name: string;
    description?: string;
    environmentPermissionScheme?: EnvironmentPermissionSchemeWritable;
    status?: EnvironmentStatus;
    url?: string;
    deployment?: DeploymentResponseWritable;
    parent?: NamedReference;
    tiers?: Array<NamedReference>;
    incomingDependencies?: Array<NamedReference>;
    outgoingDependencies?: Array<NamedReference>;
    attributes?: {
        [key: string]: string;
    };
};

export type EnvironmentWatcherWritable = {
    userKey?: string;
    userName?: string;
    environmentId: number;
    watchEnvironmentChanged: boolean;
    watchDeployedVersion: boolean;
    watchStatus: boolean;
    watchIssueAdded: boolean;
    watchIssueRemoved: boolean;
};

export type DeploymentDetailWritable = {
    versionName?: string;
    versionId?: string;
    /**
     * ISO-8601 date time format
     */
    deployedOn?: string;
    buildNumber?: string;
    description?: string;
    issueKeys?: Array<string>;
    attributes?: unknown;
};

export type PostApplicationData = {
    /**
     * An application request
     */
    body: ApplicationRequest;
    path?: never;
    query?: never;
    url: '/application';
};

export type PostApplicationErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostApplicationError = PostApplicationErrors[keyof PostApplicationErrors];

export type PostApplicationResponses = {
    /**
     * successful operation
     */
    200: ApplicationResponse;
};

export type PostApplicationResponse = PostApplicationResponses[keyof PostApplicationResponses];

export type DeleteApplicationByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/application/{id}';
};

export type DeleteApplicationByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type DeleteApplicationByIdError = DeleteApplicationByIdErrors[keyof DeleteApplicationByIdErrors];

export type DeleteApplicationByIdResponses = {
    /**
     * successful operation
     */
    200: unknown;
};

export type GetApplicationByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/application/{id}';
};

export type GetApplicationByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetApplicationByIdError = GetApplicationByIdErrors[keyof GetApplicationByIdErrors];

export type GetApplicationByIdResponses = {
    /**
     * successful operation
     */
    200: ApplicationResponse;
};

export type GetApplicationByIdResponse = GetApplicationByIdResponses[keyof GetApplicationByIdResponses];

export type PutApplicationByIdData = {
    /**
     * An application request
     */
    body: ApplicationRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/application/{id}';
};

export type PutApplicationByIdErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type PutApplicationByIdError = PutApplicationByIdErrors[keyof PutApplicationByIdErrors];

export type PutApplicationByIdResponses = {
    /**
     * successful operation
     */
    200: ApplicationResponse;
};

export type PutApplicationByIdResponse = PutApplicationByIdResponses[keyof PutApplicationByIdResponses];

export type GetApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Set it to false for lighter JSON
         */
        _expand?: boolean;
    };
    url: '/applications';
};

export type GetApplicationsResponses = {
    /**
     * successful operation
     */
    200: Array<ApplicationResponse>;
};

export type GetApplicationsResponse = GetApplicationsResponses[keyof GetApplicationsResponses];

export type PostCategoryData = {
    /**
     * A category
     */
    body: EnvironmentCategory;
    path?: never;
    query?: never;
    url: '/category';
};

export type PostCategoryErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostCategoryError = PostCategoryErrors[keyof PostCategoryErrors];

export type PostCategoryResponses = {
    /**
     * successful operation
     */
    200: EnvironmentCategory;
};

export type PostCategoryResponse = PostCategoryResponses[keyof PostCategoryResponses];

export type DeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/category/{id}';
};

export type DeleteErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
    /**
     * successful operation
     */
    200: EnvironmentCategory;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type GetCategoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/category/{id}';
};

export type GetCategoryByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetCategoryByIdError = GetCategoryByIdErrors[keyof GetCategoryByIdErrors];

export type GetCategoryByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentCategory;
};

export type GetCategoryByIdResponse = GetCategoryByIdResponses[keyof GetCategoryByIdResponses];

export type PutCategoryByIdData = {
    /**
     * a category
     */
    body: EnvironmentCategory;
    path: {
        id: number;
    };
    query?: never;
    url: '/category/{id}';
};

export type PutCategoryByIdErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type PutCategoryByIdError = PutCategoryByIdErrors[keyof PutCategoryByIdErrors];

export type PutCategoryByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentCategory;
};

export type PutCategoryByIdResponse = PutCategoryByIdResponses[keyof PutCategoryByIdResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type GetCategoriesResponses = {
    /**
     * successful operation
     */
    200: Array<EnvironmentCategory>;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type PostStatusData = {
    body: EnvironmentStatus;
    path?: never;
    query?: never;
    url: '/status';
};

export type PostStatusErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostStatusError = PostStatusErrors[keyof PostStatusErrors];

export type PostStatusResponses = {
    /**
     * successful operation
     */
    200: EnvironmentStatus;
};

export type PostStatusResponse = PostStatusResponses[keyof PostStatusResponses];

export type DeleteStatusByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/status/{id}';
};

export type DeleteStatusByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type DeleteStatusByIdError = DeleteStatusByIdErrors[keyof DeleteStatusByIdErrors];

export type DeleteStatusByIdResponses = {
    /**
     * successful operation
     */
    200: unknown;
};

export type GetStatusByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/status/{id}';
};

export type GetStatusByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetStatusByIdError = GetStatusByIdErrors[keyof GetStatusByIdErrors];

export type GetStatusByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentStatus;
};

export type GetStatusByIdResponse = GetStatusByIdResponses[keyof GetStatusByIdResponses];

export type PutStatusByIdData = {
    body: EnvironmentStatus;
    path: {
        id: number;
    };
    query?: never;
    url: '/status/{id}';
};

export type PutStatusByIdErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type PutStatusByIdError = PutStatusByIdErrors[keyof PutStatusByIdErrors];

export type PutStatusByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentStatus;
};

export type PutStatusByIdResponse = PutStatusByIdResponses[keyof PutStatusByIdResponses];

export type GetStatusesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/statuses';
};

export type GetStatusesResponses = {
    /**
     * successful operation
     */
    200: Array<EnvironmentStatus>;
};

export type GetStatusesResponse = GetStatusesResponses[keyof GetStatusesResponses];

export type GetDeploymentData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment id. Ex: 1
         */
        environmentId?: number;
        /**
         * Application name. Ex: eCommerce
         */
        application?: string;
        /**
         * Category name. Ex: Staging
         */
        category?: string;
        /**
         * Date in the past. Ex: 2018-01-31 13:30 or in ms : 1537679702182
         */
        dateTime?: string;
        /**
         * Absolute time in ms. Ex: 12300054 . Note that time must be in
         * the past. Time will override dateTime param if both params are set.
         *
         */
        time?: number;
    };
    url: '/deployment';
};

export type GetDeploymentErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetDeploymentError = GetDeploymentErrors[keyof GetDeploymentErrors];

export type GetDeploymentResponses = {
    /**
     * successful operation
     */
    200: DeploymentResponse;
};

export type GetDeploymentResponse = GetDeploymentResponses[keyof GetDeploymentResponses];

export type PutDeploymentData = {
    body: DeploymentRequestWritable;
    path?: never;
    query?: {
        /**
         * Environment id. Ex: 1
         */
        environmentId?: number;
        /**
         * Application name. Ex: eCommerce
         */
        application?: string;
        /**
         * Category name. Ex: Staging
         */
        category?: string;
        /**
         * Date in the past. Ex: 2018-01-31 13:30. Note that timezone of
         * the server will be used to get the time! Prefer using the time parameter
         * in ms to avoid timezone issues.
         *
         */
        dateTime?: string;
        /**
         * Absolute time in ms. Ex: 12300054 . Note that time must be in
         * the past. Time will override dateTime param if both params are set.
         *
         */
        time?: number;
    };
    url: '/deployment';
};

export type PutDeploymentErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PutDeploymentError = PutDeploymentErrors[keyof PutDeploymentErrors];

export type PutDeploymentResponses = {
    /**
     * successful operation
     */
    200: DeploymentResponse;
};

export type PutDeploymentResponse = PutDeploymentResponses[keyof PutDeploymentResponses];

export type DeleteDeploymentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/deployment/{id}';
};

export type DeleteDeploymentByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type DeleteDeploymentByIdError = DeleteDeploymentByIdErrors[keyof DeleteDeploymentByIdErrors];

export type DeleteDeploymentByIdResponses = {
    /**
     * successful operation
     */
    200: DeploymentResponse;
};

export type DeleteDeploymentByIdResponse = DeleteDeploymentByIdResponses[keyof DeleteDeploymentByIdResponses];

export type GetDeploymentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/deployment/{id}';
};

export type GetDeploymentByIdErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetDeploymentByIdError = GetDeploymentByIdErrors[keyof GetDeploymentByIdErrors];

export type GetDeploymentByIdResponses = {
    /**
     * successful operation
     */
    200: DeploymentResponse;
};

export type GetDeploymentByIdResponse = GetDeploymentByIdResponses[keyof GetDeploymentByIdResponses];

export type GetDeploymentsData = {
    body?: never;
    path?: never;
    query?: {
        environmentId?: number;
        application?: string;
        category?: string;
        /**
         * Ex: 2018-01-31
         */
        start?: string;
        /**
         * Ex: 2018-02-25
         */
        end?: string;
        /**
         * Unlimited number of results: -1
         */
        maxResults?: number;
        /**
         * Set it to false for lighter JSON
         */
        expand?: boolean;
    };
    url: '/deployments';
};

export type GetDeploymentsResponses = {
    /**
     * successful operation
     */
    200: Array<DeploymentResponse>;
};

export type GetDeploymentsResponse = GetDeploymentsResponses[keyof GetDeploymentsResponses];

export type PostDeploymentsIssueData = {
    body: IssueDeployedRequest;
    path?: never;
    query?: never;
    url: '/deployments/issue';
};

export type PostDeploymentsIssueResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type PostVersionData = {
    body: VersionInfoRequest;
    path?: never;
    query?: never;
    url: '/version';
};

export type PostVersionErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostVersionError = PostVersionErrors[keyof PostVersionErrors];

export type PostVersionResponses = {
    /**
     * successful operation
     */
    200: VersionInfoResponse;
};

export type PostVersionResponse = PostVersionResponses[keyof PostVersionResponses];

export type GetStatusChangeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment id. Ex: 1
         */
        environmentId?: number;
        /**
         * Application name. Ex: eCommerce
         */
        application?: string;
        /**
         * Category name. Ex: Staging
         */
        category?: string;
    };
    url: '/status-change';
};

export type GetStatusChangeErrors = {
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type GetStatusChangeError = GetStatusChangeErrors[keyof GetStatusChangeErrors];

export type GetStatusChangeResponses = {
    /**
     * successful operation
     */
    200: StatusChange;
};

export type GetStatusChangeResponse = GetStatusChangeResponses[keyof GetStatusChangeResponses];

export type PutStatusChangeData = {
    /**
     * Examples of valid json body:
     * {"name":"Unavailable"}
     * or
     * {id": 1}
     *
     */
    body: EnvironmentStatusChangeRequest;
    path?: never;
    query?: {
        /**
         * Environment id. Ex: 1
         */
        environmentId?: number;
        /**
         * Application name. Ex: eCommerce
         */
        application?: string;
        /**
         * Category name. Ex: Staging
         */
        category?: string;
    };
    url: '/status-change';
};

export type PutStatusChangeErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
    /**
     * Resource has not been found.
     */
    404: ErrorCollection;
};

export type PutStatusChangeError = PutStatusChangeErrors[keyof PutStatusChangeErrors];

export type PutStatusChangeResponses = {
    /**
     * successful operation
     */
    200: StatusChange;
};

export type PutStatusChangeResponse = PutStatusChangeResponses[keyof PutStatusChangeResponses];

export type GetStatusChangesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment id. Ex: 1
         */
        environmentId?: number;
        /**
         * Application name. Ex: eCommerce
         */
        application?: string;
        /**
         * Category name. Ex: Staging
         */
        category?: string;
        /**
         * Ex: 2018-01-31
         */
        start?: string;
        /**
         * Ex: 2019-01-31
         */
        end?: string;
        /**
         * Unlimited number of results: -1
         */
        maxResult?: number;
        /**
         * Set it to false for lighter JSON
         */
        expand?: boolean;
    };
    url: '/status-changes';
};

export type GetStatusChangesResponses = {
    /**
     * successful operation
     */
    200: Array<StatusChange>;
};

export type GetStatusChangesResponse = GetStatusChangesResponses[keyof GetStatusChangesResponses];

export type PostStatusChangesData = {
    body: ScopedStatusChangeRequest;
    path?: never;
    query?: never;
    url: '/status-changes';
};

export type PostStatusChangesErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostStatusChangesError = PostStatusChangesErrors[keyof PostStatusChangesErrors];

export type PostStatusChangesResponses = {
    /**
     * successful operation
     */
    200: StatusChangesResponse;
};

export type PostStatusChangesResponse = PostStatusChangesResponses[keyof PostStatusChangesResponses];

export type PutStatusChangesData = {
    body: ScopedStatusChangeRequest;
    path?: never;
    query?: never;
    url: '/status-changes';
};

export type PutStatusChangesErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PutStatusChangesError = PutStatusChangesErrors[keyof PutStatusChangesErrors];

export type PutStatusChangesResponses = {
    /**
     * successful operation
     */
    200: StatusChangesResponse;
};

export type PutStatusChangesResponse = PutStatusChangesResponses[keyof PutStatusChangesResponses];

export type GetEnvironmentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Application name. Ex: eCommerce
         */
        application: string;
        /**
         * Category name. Ex: Staging
         */
        category: string;
    };
    url: '/environment';
};

export type GetEnvironmentResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type GetEnvironmentResponse = GetEnvironmentResponses[keyof GetEnvironmentResponses];

export type PostEnvironmentData = {
    /**
     * Example of realistic body: <pre><code>{
     * "application": { "name": "eCommerce" },
     * "category": { "name":"Staging" },
     * "environmentPermissionScheme": { "id": 1 },
     * "url": "https://ecom-staging-my-company.com/welcome",
     * "attributes": {
     * "OS": "RedHat 7",
     * "database": "postgres",
     * "location": "EU"
     * }
     * }</code></pre>
     */
    body: EnvironmentRequest;
    path?: never;
    query?: never;
    url: '/environment';
};

export type PostEnvironmentResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type PostEnvironmentResponse = PostEnvironmentResponses[keyof PostEnvironmentResponses];

export type PostEnvironmentCloneData = {
    body: CloneEnvironmentRequest;
    path?: never;
    query?: never;
    url: '/environment/clone';
};

export type PostEnvironmentCloneResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type PostEnvironmentCloneResponse = PostEnvironmentCloneResponses[keyof PostEnvironmentCloneResponses];

export type DeleteEnvironmentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/environment/{id}';
};

export type DeleteEnvironmentByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type DeleteEnvironmentByIdResponse = DeleteEnvironmentByIdResponses[keyof DeleteEnvironmentByIdResponses];

export type GetEnvironmentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/environment/{id}';
};

export type GetEnvironmentByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type GetEnvironmentByIdResponse = GetEnvironmentByIdResponses[keyof GetEnvironmentByIdResponses];

export type PutEnvironmentByIdData = {
    /**
     * Example: set url and some attributes: <pre><code>{
     * "url": "https://ecom-staging-my-company.com/welcome/NEWURL",
     * "attributes": {
     * "OS": "RedHat 8",
     * "database": "mongo",
     * "location": "US"
     * }
     * }</code></pre><br/>Example: change application and category: <pre><code>{
     * "application": {
     * "name": "Payment Service"
     * },
     * "category": {
     * "name": "Demo"
     * }
     * }</code></pre>
     */
    body: EnvironmentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/environment/{id}';
};

export type PutEnvironmentByIdResponses = {
    /**
     * successful operation
     */
    200: EnvironmentResponse;
};

export type PutEnvironmentByIdResponse = PutEnvironmentByIdResponses[keyof PutEnvironmentByIdResponses];

export type PostEnvironmentInformationData = {
    body: EnvironmentInfoRequest;
    path?: never;
    query?: never;
    url: '/environment/information';
};

export type PostEnvironmentInformationErrors = {
    /**
     * Request was invalid, reason should be provided in response body.
     */
    400: ErrorCollection;
};

export type PostEnvironmentInformationError = PostEnvironmentInformationErrors[keyof PostEnvironmentInformationErrors];

export type PostEnvironmentInformationResponses = {
    /**
     * successful operation
     */
    200: EnvironmentInfoResponse;
};

export type PostEnvironmentInformationResponse = PostEnvironmentInformationResponses[keyof PostEnvironmentInformationResponses];

export type GetEnvironmentsSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Application name (ex: eCommerce)
         */
        applicationName?: Array<string>;
        /**
         * Application id (ex: 23)
         */
        applicationId?: Array<number>;
        /**
         * Category Name (ex: Staging)
         */
        categoryName?: Array<string>;
        /**
         * Category id (ex: 2)
         */
        categoryId?: Array<number>;
        /**
         * Status Name (ex: Slow)
         */
        statusName?: Array<string>;
        /**
         * Status id (ex: 3)
         */
        statusId?: Array<number>;
        /**
         * Permission scheme name (ex: Default Environment Permission Scheme)
         */
        permissionSchemeName?: Array<string>;
        /**
         * Permission scheme id (ex: 1)
         */
        permissionSchemeId?: Array<number>;
        /**
         * Max number of results (0 = unlimited)
         */
        _limit?: number;
        /**
         * First result to return (ex: 10)
         */
        _offset?: number;
        /**
         * Sort order
         */
        _sortOrder?: string;
        /**
         * Sort by
         */
        _sortBy?: string;
        /**
         * Set it to false for lighter JSON
         */
        _expand?: boolean;
    };
    url: '/environments/search';
};

export type GetEnvironmentsSearchResponses = {
    /**
     * successful operation
     */
    200: Array<EnvironmentResponse>;
};

export type GetEnvironmentsSearchResponse = GetEnvironmentsSearchResponses[keyof GetEnvironmentsSearchResponses];

export type PostEnvironmentsSearchData = {
    body: EnvironmentFilter;
    path?: never;
    query?: never;
    url: '/environments/search';
};

export type PostEnvironmentsSearchResponses = {
    /**
     * successful operation
     */
    200: Array<EnvironmentResponse>;
};

export type PostEnvironmentsSearchResponse = PostEnvironmentsSearchResponses[keyof PostEnvironmentsSearchResponses];

export type GetEnvironmentsSearchPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment id (ex: 23)
         */
        environmentId?: Array<number>;
        /**
         * Environment name (ex: eCommerce Dev 1)
         */
        environmentName?: Array<string>;
        /**
         * Application name (ex: eCommerce)
         */
        applicationName?: Array<string>;
        /**
         * Application id (ex: 23)
         */
        applicationId?: Array<number>;
        /**
         * Category Name (ex: Staging)
         */
        categoryName?: Array<string>;
        /**
         * Category id (ex: 2)
         */
        categoryId?: Array<number>;
        /**
         * Status Name (ex: Slow)
         */
        statusName?: Array<string>;
        /**
         * Status id (ex: 3)
         */
        statusId?: Array<number>;
        /**
         * Permission scheme name (ex: Default Environment Permission Scheme)
         */
        permissionSchemeName?: Array<string>;
        /**
         * Permission scheme id (ex: 1)
         */
        permissionSchemeId?: Array<number>;
        /**
         * Panel scheme id (ex: 1)
         */
        panelSchemeId?: Array<number>;
        /**
         * Tier relation type (ex: HAS_TIERS, HAS_NO_TIERS, HAS_PARENT, IS_TIER, IS_ORPHAN)
         */
        tierRelation?: Array<string>;
        /**
         * Max number of results (0 = unlimited)
         */
        _limit?: number;
        /**
         * First result to return (ex: 10)
         */
        _offset?: number;
        /**
         * Sort order
         */
        _sortOrder?: string;
        /**
         * Sort by
         */
        _sortBy?: string;
        /**
         * Set it to false for lighter JSON
         */
        _expand?: boolean;
    };
    url: '/environments/search/paginated';
};

export type GetEnvironmentsSearchPaginatedResponses = {
    /**
     * successful operation
     */
    200: PaginatedEnvironmentResponse;
};

export type GetEnvironmentsSearchPaginatedResponse = GetEnvironmentsSearchPaginatedResponses[keyof GetEnvironmentsSearchPaginatedResponses];

export type PostEnvironmentsSearchPaginatedData = {
    /**
     * search filter object
     */
    body: EnvironmentFilter;
    path?: never;
    query?: never;
    url: '/environments/search/paginated';
};

export type PostEnvironmentsSearchPaginatedResponses = {
    /**
     * successful operation
     */
    200: PaginatedEnvironmentResponse;
};

export type PostEnvironmentsSearchPaginatedResponse = PostEnvironmentsSearchPaginatedResponses[keyof PostEnvironmentsSearchPaginatedResponses];

export type GetWatcherStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/watcher/statistics';
};

export type GetWatcherStatisticsResponses = {
    /**
     * successful operation
     */
    200: WatcherStatistics;
};

export type GetWatcherStatisticsResponse = GetWatcherStatisticsResponses[keyof GetWatcherStatisticsResponses];

export type DeleteWatcherUserData = {
    body?: never;
    path?: never;
    query: {
        environmentId: number;
        userName?: string;
        userKey?: string;
    };
    url: '/watcher/user';
};

export type DeleteWatcherUserResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type GetWatcherUserData = {
    body?: never;
    path?: never;
    query: {
        environmentId: number;
        userName?: string;
        userKey?: string;
    };
    url: '/watcher/user';
};

export type GetWatcherUserResponses = {
    /**
     * successful operation
     */
    200: EnvironmentWatcher;
};

export type GetWatcherUserResponse = GetWatcherUserResponses[keyof GetWatcherUserResponses];

export type PostWatcherUserData = {
    body: EnvironmentWatcherWritable;
    path?: never;
    query: {
        environmentId: number;
        userName?: string;
        userKey?: string;
    };
    url: '/watcher/user';
};

export type PostWatcherUserResponses = {
    /**
     * successful operation
     */
    200: EnvironmentWatcher;
};

export type PostWatcherUserResponse = PostWatcherUserResponses[keyof PostWatcherUserResponses];

export type PutWatcherUserData = {
    body: EnvironmentWatcherWritable;
    path?: never;
    query: {
        environmentId: number;
        userName?: string;
        userKey?: string;
    };
    url: '/watcher/user';
};

export type PutWatcherUserResponses = {
    /**
     * successful operation
     */
    200: EnvironmentWatcher;
};

export type PutWatcherUserResponse = PutWatcherUserResponses[keyof PutWatcherUserResponses];
