name: Test Bump and Release Main
on:
  workflow_dispatch:
  push:
      branches:
        - 'main'
      paths:
        - '**.js'
        - '**.ts'
        - '**.json'
        - '**.yml'
jobs:
  tests:
    name: Ensure tests and builds are OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
#      - run: npm test
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  bump-and-publish:
    needs: [tests]
    name: 'Automated Version Bump'
    if: "success() && !startsWith(github.event.head_commit.message, 'chore: version bump')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.capture.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump
        if: success()
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'BREAKING'
          default: 'minor'
          commit-message: 'chore: version bump to {{version}}'
      - uses: actions/setup-node@v4
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          node-version-file: .node-version
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Capture actions version
        id: capture
        run: echo "version=$(npm pkg get version)" >> "$GITHUB_OUTPUT"
      - name: Publish
        run: npm publish
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  bump-send-environment-info-action:
    needs: bump-and-publish
    name: 'Automated Github Actions Update'
    if: "success()"
    defaults:
      run:
        working-directory: 'actions/golive-send-environment-info'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout golive-send-environment-info
        with:
          repository: apwide/golive-send-environment-info
          ref: main
          path: ./actions/golive-send-environment-info
          token: ${{secrets.CI_GITHUB_TOKEN}}
      - uses: actions/setup-node@v4
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          node-version-file: ./actions/golive-send-environment-info/.node-version
      - name: bump-actions
        run: |
          npm config set save-exact true
          npm install @apwide/golive-github-actions@${{ needs.bump-and-publish.outputs.version }}
      - name: Install
        run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name 'Apwide CI'
          git config --global user.email 'ci@apwide.com'
          git add -A
          git commit -am "chore: bumped golive-github-actions to ${{ needs.bump-and-publish.outputs.version }}"
          git push

  bump-send-release-info-action:
    needs: bump-and-publish
    name: 'Automated Github Actions Update'
    if: "success()"
    defaults:
      run:
        working-directory: 'actions/golive-send-release-info'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout golive-send-release-info
        with:
          repository: apwide/golive-send-release-info
          ref: main
          path: ./actions/golive-send-release-info
          token: ${{secrets.CI_GITHUB_TOKEN}}
      - uses: actions/setup-node@v4
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          node-version-file: ./actions/golive-send-release-info/.node-version
      - name: bump-actions
        run: |
          npm config set save-exact true
          npm install @apwide/golive-github-actions@${{ needs.bump-and-publish.outputs.version }}
      - name: Install
        run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name 'Apwide CI'
          git config --global user.email 'ci@apwide.com'
          git add -A
          git commit -am "chore: bumped golive-github-actions to ${{ needs.bump-and-publish.outputs.version }}"
          git push

