name: release
on:
  workflow_dispatch:
  push:
      branches:
        - 'release/**'
permissions:
  id-token: write
  contents: write
jobs:
  bump-and-publish:
    name: 'Build, Release & Publish'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.capture.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Bump
        if: success()
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'BREAKING'
          default: 'minor'
          commit-message: 'chore: version bump to {{version}}'
      - uses: actions/setup-node@v7
        env: {}
        with:
          node-version-file: .node-version
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build
#        npm run test
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Capture version
        id: capture
        run: |
          ACTION_VERSION=$(npm pkg get version | sed 's/"//g')
          echo "version=$ACTION_VERSION" >> $GITHUB_OUTPUT
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "OUTPUT=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
#      - name: Publish
#        run: npm publish
#        env: {}

  bump-send-environment-info-action:
    needs: bump-and-publish
    name: 'Bump golive-send-environment-info'
    if: "success()"
    defaults:
      run:
        working-directory: 'actions/golive-send-environment-info'
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        id: print_output
        run: |
          echo "PREV_OUTPUT=${{ needs.bump-and-publish.outputs.branch }}"
      - uses: actions/checkout@v7
        name: checkout golive-send-environment-info
        with:
          repository: apwide/golive-send-environment-info
          ref: ${{ needs.bump-and-publish.outputs.branch }}
          path: ./actions/golive-send-environment-info
          token: ${{secrets.CI_GITHUB_TOKEN}}
      - run: |
          git config --global user.name 'Apwide CI'
          git config --global user.email 'ci@apwide.com'
      - uses: actions/setup-node@v7
        env: {}
        with:
          node-version-file: ./actions/golive-send-environment-info/.node-version
      - name: bump-actions
        run: |
          npm config set save-exact true
          npm install @apwide/golive-github-actions@${{ needs.bump-and-publish.outputs.version }}
          npm ci
          npm run build
      - name: push
        run: |
          git add -A
          git commit -am "chore: bumped golive-github-actions to ${{ needs.bump-and-publish.outputs.version }}"
          git push

  bump-send-release-info-action:
    needs: bump-and-publish
    name: 'Bump golive-send-release-info'
    if: "success()"
    defaults:
      run:
        working-directory: 'actions/golive-send-release-info'
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        id: print_output
        run: |
          echo "PREV_OUTPUT=${{ needs.bump-and-publish.outputs.branch }}"
      - uses: actions/checkout@v7
        name: checkout golive-send-release-info
        with:
          repository: apwide/golive-send-release-info
          ref: ${{ needs.bump-and-publish.outputs.branch }}
          path: ./actions/golive-send-release-info
          token: ${{secrets.CI_GITHUB_TOKEN}}
      - run: |
          git config --global user.name 'Apwide CI'
          git config --global user.email 'ci@apwide.com'
      - uses: actions/setup-node@v7
        env: {}
        with:
          node-version-file: ./actions/golive-send-release-info/.node-version
      - name: bump-actions
        run: |
          npm config set save-exact true
          npm install @apwide/golive-github-actions@${{ needs.bump-and-publish.outputs.version }}
          npm ci
          npm run build
      - name: push
        run: |
          git add -A
          git commit -am "chore: bumped golive-github-actions to ${{ needs.bump-and-publish.outputs.version }}"
          git push
